# Generated by Django 3.1 on 2020-09-11 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300, null=True)),
                ('contect', models.PositiveIntegerField()),
                ('landline', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('business', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(null=True)),
                ('product', models.PositiveIntegerField(null=True)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('delivery', models.BooleanField(default=False, null=True)),
                ('item', models.PositiveIntegerField(default=False, null=True)),
                ('total', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OredProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(null=True)),
                ('product', models.PositiveIntegerField(null=True)),
                ('count', models.PositiveIntegerField(default=1, null=True)),
                ('total', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('druglicenceNo', models.CharField(max_length=100, null=True)),
                ('gstin', models.CharField(max_length=100, null=True)),
                ('druglicence', models.ImageField(blank=True, upload_to='DrugLicence')),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contect', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contect', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imfu_online.category')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('subcategory', models.CharField(max_length=200, null=True)),
                ('batchno', models.PositiveIntegerField(null=True)),
                ('expdate', models.DateField(null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('capacity', models.PositiveIntegerField(null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('ptr', models.PositiveIntegerField(default=0, null=True)),
                ('dptr', models.PositiveIntegerField(default=0, null=True)),
                ('mrp', models.PositiveIntegerField(default=0, null=True)),
                ('cgst', models.PositiveIntegerField(default=0, null=True)),
                ('sgst', models.PositiveIntegerField(default=0, null=True)),
                ('offer', models.PositiveIntegerField(default=0, null=True)),
                ('composition', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deliveryboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imfu_online.vendor')),
            ],
        ),
    ]
