# Generated by Django 3.1 on 2020-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfu_online', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
