# Generated by Django 3.0.6 on 2020-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfu_online', '0002_auto_20200911_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offer',
            new_name='buy',
        ),
        migrations.AddField(
            model_name='product',
            name='get',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
