# Generated by Django 3.0.6 on 2020-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfu_online', '0003_auto_20200920_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cgst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dptr',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='get',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ptr',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sgst',
            field=models.FloatField(default=0, null=True),
        ),
    ]
