# Generated by Django 3.1.1 on 2020-09-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfu_online', '0004_auto_20200920_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='zone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
