# Generated by Django 3.1.1 on 2020-09-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imfu_online', '0006_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='landline',
        ),
    ]
